name: OPTIMADE validator
description: Validate your OPTIMADE server using the optimade-python-tools validator
author: Casper Welzel Andersen, Matthew Evans
branding:
  icon: server
  color: green

inputs:

  all versioned paths:
    description: >
      Whether to test all possible versioned base URLs:
        /vMAJOR; /vMAJOR.MINOR; /vMAJOR.MINOR.PATCH
      If this is 'true', the input 'path' MUST exempt the version part (e.g., '/optimade' instead of '/optimade/v0').
      If this is 'false', the input 'path' MUST include the version part (e.g., '/optimade/v0' instead of '/optimade').
    required: false
    default: false

  as type:
    description: >
      Validate the request URL with the provided type, rather than scanning the entire implementation.
      Example values: 'structures', 'reference'. For a full list of values see `optimade-python-tools`.
    required: false

  domain:
    description: Domain for the OPTIMADE URL (defaults to the GH Actions runner host)
    required: false
    default: gh_actions_host

  fail fast:
    description: Whether or not to exit and return a non-zero error code on first failure.
    required: false
    default: false

  index:
    description: Whether or not this is an index meta-database
    required: false
    default: false

  path:
    description: Path of the OPTIMADE (versioned) base URL - MUST start with '/'
    required: false
    default: /v0

  port:
    description: Port for the OPTIMADE URL
    required: false

  protocol:
    description: Protocol for the OPTIMADE URL
    required: false
    default: http

  skip optional:
    description: Whether or not to skip tests for optional features.
    required: false
    default: false

  validator version:
    description: >
      Full version of an OPTIMADE Python tools release to PyPI, e.g., '0.6.0' or '0.3.4', which hosts the `optimade_validator`.
      It can also be a branch, tag, or git commit to use from the GitHub repository, e.g., 'master', 'v0.6.0' or '5a5e903'.
      See https://pip.pypa.io/en/latest/reference/pip_install/#git for more information of what is allowed here.
      Finally, it may also be 'latest' (default), which is understood to be the latest official release of the `optimade` package on PyPI.
      Note, for the latest development version, choose 'master'.
    required: true
    default: latest

  verbosity:
    description: The verbosity of the output
    required: false
    default: 1

runs:
  using: 'docker'
  image: 'Dockerfile'
