name: OPTIMADE validator
description: Validate your OPTIMADE server using the optimade-python-tools validator
author: Casper Welzel Andersen, Matthew Evans
branding:
  icon: server
  color: green

inputs:

  all versioned paths:
    description: >
      Whether to test the optional versioned URLs:
        /vMAJOR.MINOR; /vMAJOR.MINOR.PATCH
      If false, only the mandatory /vMAJOR url will be tested.
    required: false
    default: false

  validate unversioned paths:
      description: >
        Whether to validate the input URL as a full OPTIMADE implementation without appending any version.
        This action assumes that the `path` parameter will contain an unversioned URL.
        As it is not mandatory to run a full OPTIMADE implementation from the unversioned URL,
        by default, this action will not perform any validation of this URL, beyond checking
        the `/versions` endpoint.
      required: false
      default: false

  as type:
    description: >
      Validate the request URL with the provided type, rather than scanning the entire implementation.
      Example values: 'structures', 'reference'. For a full list of values see `optimade-python-tools`.
    required: false

  domain:
    description: Domain for the OPTIMADE URL (defaults to the GH Actions runner host).
    required: false
    default: gh_actions_host

  fail fast:
    description: Whether or not to exit and return a non-zero error code on first failure.
    required: false
    default: false

  index:
    description: Whether or not this is an index meta-database.
    required: false
    default: false

  create output:
    description: >
      Use `-j/--json` option for `optimade-validator`.
      This will overwrite the `verbosity` input parameter, since it will be set to `-1` when using the `-j/--json` option.
    required: false
    default: false

  path:
    description: >
      Path to append to the domain to reach the OPTIMADE unversioned base URL - MUST start with `/`.
      The path MUST NOT include the versioned part of the base URL.
      Rather, it MUST point to the unversioned base URL of your OPTIMADE implementation.
    required: false
    default: /

  port:
    description: Port for the OPTIMADE URL.
    required: false

  protocol:
    description: Protocol for the OPTIMADE URL.
    required: false
    default: http

  skip optional:
    description: Whether or not to skip tests for optional features.
    required: false
    default: false

  validator version:
    description: >
      Full version of an OPTIMADE Python tools release to PyPI, e.g., '0.6.0' or '0.3.4', which hosts the `optimade-validator`.
      It can also be a branch, tag, or git commit to use from the GitHub repository, e.g., 'master', 'v0.6.0' or '5a5e903'.
      See https://pip.pypa.io/en/latest/reference/pip_install/#git for more information of what is allowed here.
      Finally, it may also be 'latest' (default), which is understood to be the latest official release of the `optimade` package on PyPI.
      Note, for the latest development version, choose 'master'.
    required: true
    default: latest

  verbosity:
    description: The verbosity of the output
    required: false
    default: 1

outputs:

  results:
    description: >
      JSON object with results overview from `optimade-validator`.
      This is equivalent to passing `-j/--json` to `optimade-validator`.
      NOTE: This is only set if `create output` is set to `True`.

runs:
  using: 'docker'
  image: 'Dockerfile'
