name: CI - Single Dependabot PR

on:
  schedule:
    # At 6:30 UTC every Wednesday
    # Dependabot runs daily at between 4 and 5 UTC
    - cron: "30 6 * * 3"

jobs:

  create-collected-pr:
    name: Single dependabot PR
    if: github.repository_owner == 'Materials-Consortia'
    runs-on: ubuntu-latest
    env:
      DEPENDABOT_BRANCH: ci/dependabot-updates
      GIT_USER_NAME: OPTIMADE Developers
      GIT_USER_EMAIL: "dev@optimade.org"
      DEFAULT_REPO_BRANCH: master

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.DEFAULT_REPO_BRANCH }}

    - name: Set up git user info
      run: |
        git config --global user.name "${{ env.GIT_USER_NAME }}"
        git config --global user.email "${{ env.GIT_USER_EMAIL }}"

    - name: Reset to '${{ env.DEPENDABOT_BRANCH }}'
      run: |
        git fetch origin ${{ env.DEPENDABOT_BRANCH }}:${{ env.DEPENDABOT_BRANCH }}
        git reset --hard ${{ env.DEPENDABOT_BRANCH }}

    - name: Fetch PR body
      id: pr_body
      uses: chuhlomin/render-template@v1.2
      with:
        template: .github/utils/single_dependency_pr_body.txt

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.RELEASE_PAT_CASPER }}
        commit-message: New @dependabot-fueled updates
        committer: "${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>"
        author: "${{ env.GIT_USER_NAME }} <${{ env.GIT_USER_EMAIL }}>"
        branch: ci/update-dependencies
        delete-branch: true
        title: Update dependencies
        body: ${{ steps.pr_body.outputs.result }}
        labels: CI,docker_dependencies,tests

    - name: Information
      run: 'echo "${{ steps.cpr.outputs.pull-request-operation }} PR #${{ steps.cpr.outputs.pull-request-number }}: ${{ steps.cpr.outputs.pull-request-url }}"'
