name: Test optimade-validator GitHub Action

on:
  pull_request:
  push:
    branches:
    - master

jobs:

  validator_regular:
    runs-on: ubuntu-latest
    name: Regular server

    steps:
      - uses: actions/checkout@v2

      - name: Set up and run regular server
        run: |
          git clone --recurse-submodules https://github.com/Materials-Consortia/optimade-python-tools
          docker-compose -f ./optimade-python-tools/docker-compose.yml up optimade &
          .github/workflows/wait_for_it.sh localhost:3213 -t 120
          sleep 15

      - name: Run action
        uses: ./
        with:
          port: 3213
          path: /v1

  validator_index:
    runs-on: ubuntu-latest
    name: Index server

    steps:
      - uses: actions/checkout@v2

      - name: Set up and run index server
        run: |
          git clone --recurse-submodules https://github.com/Materials-Consortia/optimade-python-tools
          docker-compose -f ./optimade-python-tools/docker-compose.yml up optimade-index &
          .github/workflows/wait_for_it.sh localhost:3214 -t 120
          sleep 15

      - name: Run action
        uses: ./
        with:
          port: 3214
          path: /v1
          index: yes

  all_versioned_paths:
    runs-on: ubuntu-latest
    name: All versioned paths for regular server

    steps:
      - uses: actions/checkout@v2

      - name: Set up and run regular server (which includes all versioned base URLs)
        run: |
          git clone --recurse-submodules https://github.com/Materials-Consortia/optimade-python-tools
          docker-compose -f ./optimade-python-tools/docker-compose.yml up optimade &
          .github/workflows/wait_for_it.sh localhost:3213 -t 120
          sleep 15

      - name: Run action
        uses: ./
        with:
          port: 3213
          path: /
          all versioned paths: yes

      - name: Run action (setting path to empty string)
        uses: ./
        with:
          port: 3213
          path: ""
          all versioned paths: yes

  bats:
    runs-on: ubuntu-latest
    name: Run BATS test suite for entrypoint.sh

    steps:
      - uses: actions/checkout@v2

      - name: Build BATS environment
        run: docker build -t optimade_bats ./tests

      - name: Run BATS tests
        run: ./run_tests.sh

  validator_version:
    runs-on: ubuntu-latest
    name: Use validator from git commit sha

    steps:
      - uses: actions/checkout@v2

      - name: Set up and run regular server
        run: |
          git clone --recurse-submodules https://github.com/Materials-Consortia/optimade-python-tools
          docker-compose -f ./optimade-python-tools/docker-compose.yml up optimade &
          .github/workflows/wait_for_it.sh localhost:3213 -t 120
          sleep 15

      - name: Run action
        uses: ./
        with:
          port: 3213
          path: /v1
          validator version: 93e50b1
